{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bankapp.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
