{{- if .Values.externalSecrets.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.name }}

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.databaseSecretKey }}
        property: {{ .Values.externalSecrets.hostProperty }}
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.databaseSecretKey }}
        property: {{ .Values.externalSecrets.portProperty }}
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.databaseSecretKey }}
        property: {{ .Values.externalSecrets.usernameProperty }}
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.rdsPasswordSecretKey }}
        property: {{ .Values.externalSecrets.passwordProperty }}
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.externalSecrets.databaseSecretKey }}
        property: {{ .Values.externalSecrets.dbnameProperty }}

{{- end }}
