{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bankapp.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
