apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bankapp
  labels:
    app: backend
spec:
  replicas: 2

  serviceAccountName: backend
  automountServiceAccountToken: false

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: backend
          image: 020139096715.dkr.ecr.ap-south-1.amazonaws.com/eks-platform-dev-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          # Here we are using external secrets to get the database credentials from AWS Secrets Manager
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_NAME

          resources:
            requests:
              memory: "120Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "500m"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
